'use strict';
const $=id=>document.getElementById(id);
let config, current=null, busy=false, recognition=null, listening=false, latestReply='';
function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function error(text){$('error').textContent=text;$('error').hidden=!text;}
function voiceStatus(text){$('voice-status').textContent=text;}
function stopListening(){listening=false;$('listen').classList.remove('listening');$('listen').setAttribute('aria-pressed','false');$('listen').innerHTML='<span aria-hidden="true">●</span> Speak to FixProof';}
function setupVoice(){
  const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;
  if(!SpeechRecognition){$('listen').disabled=true;voiceStatus('Voice input is unavailable in this browser. Type your question below.');}
  else{
    recognition=new SpeechRecognition();recognition.lang='en-AU';recognition.continuous=false;recognition.interimResults=true;
    recognition.onstart=()=>{listening=true;$('listen').classList.add('listening');$('listen').setAttribute('aria-pressed','true');$('listen').textContent='Listening… press to stop';voiceStatus('Listening. Your words will appear in the question box for review.');};
    recognition.onresult=e=>{let text='';for(let i=e.resultIndex;i<e.results.length;i++)text+=e.results[i][0].transcript;$('message').value=text.trim();$('message').dispatchEvent(new Event('input'));voiceStatus(e.results[e.results.length-1].isFinal?'Transcript ready. Review it, then press Ask FixProof.':'Listening… '+text.trim());};
    recognition.onerror=e=>{const friendly=e.error==='not-allowed'?'Microphone access was not granted. You can keep typing instead.':'Voice input stopped: '+e.error+'. You can keep typing.';voiceStatus(friendly);};
    recognition.onend=()=>{stopListening();if($('message').value.trim())voiceStatus('Transcript ready. Review it, then press Ask FixProof.');};
  }
  $('listen').onclick=()=>{if(!recognition)return;if(listening)recognition.stop();else{try{recognition.start();}catch(e){voiceStatus('Voice input is already starting.');}}};
  if(!('speechSynthesis' in window)){$('hear').disabled=true;$('hear').textContent='Spoken playback unavailable';}
  $('hear').onclick=()=>{if(!latestReply){voiceStatus('There is no FixProof response to read yet.');return;}speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(latestReply);utterance.lang='en-AU';utterance.onstart=()=>voiceStatus('Reading the latest FixProof response aloud.');utterance.onend=()=>voiceStatus('Ready for a typed or spoken question.');utterance.onerror=()=>voiceStatus('Spoken playback could not finish. The response remains visible.');speechSynthesis.speak(utterance);};
}
async function api(url,data){let key;if(data){const identity={...data};delete identity.request_id;key='fixproof-request-'+url+JSON.stringify(identity);const saved=sessionStorage.getItem(key);if(saved)data.request_id=saved;else sessionStorage.setItem(key,data.request_id);}const r=await fetch(url,data?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}:{});const value=await r.json();if(!r.ok)throw new Error(value.error||'Request failed.');if(key)sessionStorage.removeItem(key);return value;}
async function run(fn,ai=false){if(busy)return;busy=true;error('');$('loading').textContent=ai?'Working with your local AI… Your saved case is safe.':'Saving…';$('loading').hidden=false;document.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn();}catch(e){error(e.message);}finally{busy=false;$('loading').hidden=true;document.querySelectorAll('button').forEach(b=>b.disabled=false);if(current)$('chat').hidden=current.status!=='Open';}}
function modelConfig(model){const value=String(model).replace(/\s/g,'').toUpperCase();return config.models.find(entry=>entry.aliases.includes(value))||null;}
function pageLinks(container,pages,source=config.source){for(const page of pages||[]){const a=el('a','Manual · p. '+page);a.href=source.url+'#page='+page;a.target='_blank';a.rel='noopener';container.append(a);}}
async function list(){const cases=await api('/api/cases');$('cases').replaceChildren();if(!cases.length)$('cases').append(el('p','No cases yet.','muted'));for(const c of cases){const b=el('button',c.issue.slice(0,65),'case-link'+(current?.id===c.id?' active':''));b.append(el('span',(c.demo?'DEMO · ':'')+c.status));b.onclick=()=>run(()=>load(c.id));$('cases').append(b);}}
async function load(id){current=await api('/api/case?id='+encodeURIComponent(id));location.hash=current.id;render();await list();}
function render(){const c=current,catalog=modelConfig(c.model),source=catalog?.source||config.source,steps=catalog?.steps||config.steps;$('start').hidden=true;$('workspace').hidden=false;$('handover-preview').hidden=true;$('case-type').textContent=c.demo?'FICTIONAL DEMONSTRATION':'YOUR SAVED CASE';$('case-title').textContent=c.issue;$('case-model').textContent=c.model+' · '+(c.demo?'fictional model supplied':c.verified?'model confirmed by user':'model not confirmed');$('status').textContent=c.safety_report?'Stopped for safety':c.status;$('saved').textContent='Saved locally · revision '+c.revision;$('attempt-count').textContent=Object.keys(c.attempts).length+' outcomes recorded';$('events').replaceChildren();latestReply='';
for(const item of c.events){const row=el('div',undefined,'event '+item.role);row.append(el('span',item.role==='user'?'YOU':item.role==='record'?'SAVED RECORD':'FIXPROOF','role'));if(item.title)row.append(el('strong',' · '+item.title));row.append(el('p',item.step&&item.role==='record'?steps[item.step].title+' — '+item.outcome+(item.text?'\n'+item.text:''):item.text));if(item.role==='assistant')latestReply=(item.title?item.title+'. ':'')+item.text;pageLinks(row,item.pages,source);if(item.role==='record'&&item.step&&c.status==='Open'){const edit=el('button','Update this outcome','text-button');edit.onclick=()=>run(()=>action({action:'revisit',step:item.step}));row.append(edit);}if(item.trace){const d=el('details');d.append(el('summary','Local AI · '+item.trace.seconds+'s'));d.append(el('p',item.trace.model+' · '+item.trace.input_tokens+' input / '+item.trace.output_tokens+' output tokens · decision '+JSON.stringify(item.trace.decision)));row.append(d);}$('events').append(row);}
$('events').scrollTop=$('events').scrollHeight;$('message').value=localStorage.getItem('fixproof-draft-'+c.id)||'';
const pending=c.pending&&c.status==='Open';$('check-panel').hidden=!pending;if(pending){const step=steps[c.pending];$('check-title').textContent=step.title;$('check-text').textContent=step.text;$('check-sources').replaceChildren();pageLinks($('check-sources'),step.pages,source);$('result').value='';$('note').value='';}
const supported=c.verified&&!!catalog;$('reference-match').textContent=supported?'Reference matched to this case model.':'No applicable reference match for this case.';$('manual-link').hidden=!supported;$('service-link').hidden=!supported;if(supported){$('manual-link').href=source.url;$('service-link').href=source.service_url;$('source-detail').textContent=source.document+' · English (Australia)\nVerified '+source.verified;}else{$('source-detail').textContent='Record the exact model from the label; no model-specific source is applied.';}$('export').href='/api/export?id='+c.id;$('export').download='fixproof-'+c.id.slice(0,8)+'.md';$('reopen').hidden=c.status==='Open'||!!c.safety_report;$('resolved').hidden=c.status==='User reports resolved'||!!c.safety_report;$('handover').hidden=c.status==='Handover ready';$('chat').hidden=c.status!=='Open';}
async function action(data){current=await api('/api/action',{id:current.id,revision:current.revision,request_id:crypto.randomUUID(),...data});render();await list();}
$('new').onclick=()=>{if(busy)return;current=null;location.hash='';$('workspace').hidden=true;$('handover-preview').hidden=true;$('start').hidden=false;error('');list().catch(e=>error(e.message));};
$('create').onsubmit=e=>{e.preventDefault();run(async()=>{current=await api('/api/create',{request_id:crypto.randomUUID(),model:$('model').value,verified:$('verified').checked,issue:$('issue').value,demo:false});location.hash=current.id;render();await list();});};
$('demo').onclick=()=>run(async()=>{current=await api('/api/create',{request_id:crypto.randomUUID(),model:config.model,verified:true,demo:true,issue:'Plates and glasses are still wet after a wash.'});location.hash=current.id;render();$('message').value='Assess my drying issue and suggest a first check.';await list();});
$('message').oninput=()=>{if(current)localStorage.setItem('fixproof-draft-'+current.id,$('message').value);};
$('chat').onsubmit=e=>{e.preventDefault();const message=$('message').value;const id=current.id;run(async()=>{await action({action:'chat',message});localStorage.removeItem('fixproof-draft-'+id);$('message').value='';},true);};
$('outcome').onsubmit=e=>{e.preventDefault();run(()=>action({action:'outcome',step:current.pending,outcome:$('result').value,note:$('note').value}));};
$('refresh').onclick=()=>run(()=>load(current.id));
for(const [id,status] of [['handover','Handover ready'],['resolved','User reports resolved'],['reopen','Open']])$(id).onclick=()=>run(()=>action({action:'status',status}));
$('preview').onclick=()=>run(async()=>{const r=await fetch('/api/export?id='+current.id);if(!r.ok)throw new Error('Could not load handover.');$('handover-text').textContent=await r.text();$('handover-preview').hidden=false;$('handover-preview').scrollIntoView({behavior:'smooth'});});
$('close-preview').onclick=()=>{$('handover-preview').hidden=true;$('workspace').scrollIntoView({behavior:'smooth'});};
setupVoice();
run(async()=>{config=await api('/api/config');if(location.hash.length>1)await load(location.hash.slice(1));else await list();});
